version: '3.8'

services:
  web:
    build: .
    container_name: node-web-app
    ports:
      - "3000:3040"
    environment:
      - NODE_ENV=development
      - PORT=3040
      - MONGO_URI=mongodb://mongo:27017/calculator
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3040/add?num1=5&num2=2"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
